// Code generated by protoc-gen-go.
// source: rankserver.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	rankserver.proto

It has these top-level messages:
	Ranking
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Ranking struct {
}

func (m *Ranking) Reset()         { *m = Ranking{} }
func (m *Ranking) String() string { return proto1.CompactTextString(m) }
func (*Ranking) ProtoMessage()    {}

type Ranking_Nil struct {
}

func (m *Ranking_Nil) Reset()         { *m = Ranking_Nil{} }
func (m *Ranking_Nil) String() string { return proto1.CompactTextString(m) }
func (*Ranking_Nil) ProtoMessage()    {}

type Ranking_SetId struct {
	SetId uint64 `protobuf:"varint,1,opt,name=SetId" json:"SetId,omitempty"`
}

func (m *Ranking_SetId) Reset()         { *m = Ranking_SetId{} }
func (m *Ranking_SetId) String() string { return proto1.CompactTextString(m) }
func (*Ranking_SetId) ProtoMessage()    {}

type Ranking_DeleteUserRequest struct {
	SetId  uint64 `protobuf:"varint,1,opt,name=SetId" json:"SetId,omitempty"`
	UserId int32  `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *Ranking_DeleteUserRequest) Reset()         { *m = Ranking_DeleteUserRequest{} }
func (m *Ranking_DeleteUserRequest) String() string { return proto1.CompactTextString(m) }
func (*Ranking_DeleteUserRequest) ProtoMessage()    {}

type Ranking_Change struct {
	UserId int32  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	Score  int32  `protobuf:"varint,2,opt,name=Score" json:"Score,omitempty"`
	SetId  uint64 `protobuf:"varint,3,opt,name=SetId" json:"SetId,omitempty"`
}

func (m *Ranking_Change) Reset()         { *m = Ranking_Change{} }
func (m *Ranking_Change) String() string { return proto1.CompactTextString(m) }
func (*Ranking_Change) ProtoMessage()    {}

type Ranking_Range struct {
	A     int32  `protobuf:"varint,1,opt,name=A" json:"A,omitempty"`
	B     int32  `protobuf:"varint,2,opt,name=B" json:"B,omitempty"`
	SetId uint64 `protobuf:"varint,3,opt,name=SetId" json:"SetId,omitempty"`
}

func (m *Ranking_Range) Reset()         { *m = Ranking_Range{} }
func (m *Ranking_Range) String() string { return proto1.CompactTextString(m) }
func (*Ranking_Range) ProtoMessage()    {}

type Ranking_RankList struct {
	UserIds []int32 `protobuf:"varint,1,rep,packed,name=UserIds" json:"UserIds,omitempty"`
	Scores  []int32 `protobuf:"varint,2,rep,packed,name=Scores" json:"Scores,omitempty"`
}

func (m *Ranking_RankList) Reset()         { *m = Ranking_RankList{} }
func (m *Ranking_RankList) String() string { return proto1.CompactTextString(m) }
func (*Ranking_RankList) ProtoMessage()    {}

type Ranking_Users struct {
	UserIds []int32 `protobuf:"varint,1,rep,packed,name=UserIds" json:"UserIds,omitempty"`
	SetId   uint64  `protobuf:"varint,2,opt,name=SetId" json:"SetId,omitempty"`
}

func (m *Ranking_Users) Reset()         { *m = Ranking_Users{} }
func (m *Ranking_Users) String() string { return proto1.CompactTextString(m) }
func (*Ranking_Users) ProtoMessage()    {}

type Ranking_UserList struct {
	Ranks  []int32 `protobuf:"varint,1,rep,packed,name=Ranks" json:"Ranks,omitempty"`
	Scores []int32 `protobuf:"varint,2,rep,packed,name=Scores" json:"Scores,omitempty"`
}

func (m *Ranking_UserList) Reset()         { *m = Ranking_UserList{} }
func (m *Ranking_UserList) String() string { return proto1.CompactTextString(m) }
func (*Ranking_UserList) ProtoMessage()    {}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for RankingService service

type RankingServiceClient interface {
	RankChange(ctx context.Context, in *Ranking_Change, opts ...grpc.CallOption) (*Ranking_Nil, error)
	DeleteSet(ctx context.Context, in *Ranking_SetId, opts ...grpc.CallOption) (*Ranking_Nil, error)
	DeleteUser(ctx context.Context, in *Ranking_DeleteUserRequest, opts ...grpc.CallOption) (*Ranking_Nil, error)
	QueryRankRange(ctx context.Context, in *Ranking_Range, opts ...grpc.CallOption) (*Ranking_RankList, error)
	QueryUsers(ctx context.Context, in *Ranking_Users, opts ...grpc.CallOption) (*Ranking_UserList, error)
}

type rankingServiceClient struct {
	cc *grpc.ClientConn
}

func NewRankingServiceClient(cc *grpc.ClientConn) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) RankChange(ctx context.Context, in *Ranking_Change, opts ...grpc.CallOption) (*Ranking_Nil, error) {
	out := new(Ranking_Nil)
	err := grpc.Invoke(ctx, "/proto.RankingService/RankChange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) DeleteSet(ctx context.Context, in *Ranking_SetId, opts ...grpc.CallOption) (*Ranking_Nil, error) {
	out := new(Ranking_Nil)
	err := grpc.Invoke(ctx, "/proto.RankingService/DeleteSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) DeleteUser(ctx context.Context, in *Ranking_DeleteUserRequest, opts ...grpc.CallOption) (*Ranking_Nil, error) {
	out := new(Ranking_Nil)
	err := grpc.Invoke(ctx, "/proto.RankingService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) QueryRankRange(ctx context.Context, in *Ranking_Range, opts ...grpc.CallOption) (*Ranking_RankList, error) {
	out := new(Ranking_RankList)
	err := grpc.Invoke(ctx, "/proto.RankingService/QueryRankRange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) QueryUsers(ctx context.Context, in *Ranking_Users, opts ...grpc.CallOption) (*Ranking_UserList, error) {
	out := new(Ranking_UserList)
	err := grpc.Invoke(ctx, "/proto.RankingService/QueryUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RankingService service

type RankingServiceServer interface {
	RankChange(context.Context, *Ranking_Change) (*Ranking_Nil, error)
	DeleteSet(context.Context, *Ranking_SetId) (*Ranking_Nil, error)
	DeleteUser(context.Context, *Ranking_DeleteUserRequest) (*Ranking_Nil, error)
	QueryRankRange(context.Context, *Ranking_Range) (*Ranking_RankList, error)
	QueryUsers(context.Context, *Ranking_Users) (*Ranking_UserList, error)
}

func RegisterRankingServiceServer(s *grpc.Server, srv RankingServiceServer) {
	s.RegisterService(&_RankingService_serviceDesc, srv)
}

func _RankingService_RankChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ranking_Change)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RankingServiceServer).RankChange(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RankingService_DeleteSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ranking_SetId)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RankingServiceServer).DeleteSet(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RankingService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ranking_DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RankingServiceServer).DeleteUser(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RankingService_QueryRankRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ranking_Range)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RankingServiceServer).QueryRankRange(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RankingService_QueryUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ranking_Users)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RankingServiceServer).QueryUsers(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _RankingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RankChange",
			Handler:    _RankingService_RankChange_Handler,
		},
		{
			MethodName: "DeleteSet",
			Handler:    _RankingService_DeleteSet_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _RankingService_DeleteUser_Handler,
		},
		{
			MethodName: "QueryRankRange",
			Handler:    _RankingService_QueryRankRange_Handler,
		},
		{
			MethodName: "QueryUsers",
			Handler:    _RankingService_QueryUsers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
